version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vibe-storm-mysql
    restart: always
    environment:
      MYSQL_DATABASE: vibe_storm
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: vibe_user
      MYSQL_PASSWORD: vibe_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
