// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Features() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"features\" id=\"features\"><div class=\"container\"><h2>Features</h2><div class=\"features-grid\"><div class=\"feature-card\"><h3>🔐 JWT Authentication</h3><p>Secure token-based authentication with brute force protection</p></div><div class=\"feature-card\"><h3>🚀 High Performance</h3><p>Built with Go Echo framework for maximum speed and efficiency</p></div><div class=\"feature-card\"><h3>💾 MySQL Database</h3><p>Robust data persistence with GORM ORM</p></div><div class=\"feature-card\"><h3>🎨 Modern UI</h3><p>Beautiful templates with React and TypeScript support</p></div><div class=\"feature-card\"><h3>🛡️ Security First</h3><p>Rate limiting, input validation, and secure error handling</p></div><div class=\"feature-card\"><h3>🏗️ Clean Architecture</h3><p>Domain Driven Design for maintainable code</p></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
